import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { tabelasDoRepositorio, tabelasDosTextos } from "../../scripts/migracao/tabelas.mjs";
import { arquivosDaReconstrucao, lerTexto } from "../../scripts/migracao/rotinas.mjs";

/**
 * A service role usa a sequência de toda coluna que se numera sozinha.
 *
 * Ela pula o RLS, mas não a permissão, e os privilégios padrão do projeto
 * cobrem tabela, não sequência. A reconciliação do Asaas nasceu com
 * `bigserial` sem o `grant usage`: o insert da edge function levava 403, a
 * varredura respondia 200 e nada era gravado (`20261201020000`).
 *
 * A coluna `generated ... as identity` não precisaria (o Postgres não confere
 * a sequência dela), mas a regra é uma só, sem exceção por tipo de coluna: as
 * três do Vigia ganharam o grant em `20261409010000` (frente D, 07/10/2026).
 */
const RAIZ = join(__dirname, "..", "..");

const semUso = (sequencias: ReturnType<typeof tabelasDoRepositorio>["sequencias"]) =>
  [...sequencias].filter(([, s]) => !s.uso.has("service_role")).map(([nome, s]) => `${s.tabela}: ${nome}`);

describe("sequências com o uso para a service role", () => {
  const { sequencias } = tabelasDoRepositorio();

  it("as sequências foram achadas (bigserial e identity)", () => {
    expect([...sequencias.keys()]).toEqual(
      expect.arrayContaining(["reconciliacoes_asaas_id_seq", "freio_chamadas_id_seq", "ia_chamadas_id_seq", "vigia_analises_id_seq"]),
    );
  });

  it("toda sequência de coluna que se numera sozinha tem o uso para a service role", () => {
    expect(semUso(sequencias)).toEqual([]);
  });

  it("o leitor acha a tabela nova sem o grant (a trava trava)", () => {
    const textos = arquivosDaReconstrucao().map((a) => lerTexto(join(RAIZ, a)));
    const nova = tabelasDosTextos([
      ...textos,
      `create table public.com_serial (id bigserial primary key, nome text);
       create table if not exists public.com_identity (
         id bigint generated by default as identity primary key,
         valor numeric(10, 2)
       );
       create table public.com_grant (n serial, id uuid primary key);
       grant usage, select on sequence public.com_grant_n_seq to service_role;
       alter table public.alunos add column if not exists numero bigserial;
       create table public.tirada (id bigserial primary key);
       grant usage on sequence public.tirada_id_seq to service_role, authenticated;
       revoke usage on sequence public.tirada_id_seq from service_role;`,
    ]).sequencias;
    expect(semUso(nova).sort()).toEqual([
      "alunos: alunos_numero_seq",
      "com_identity: com_identity_id_seq",
      "com_serial: com_serial_id_seq",
      "tirada: tirada_id_seq",
    ]);
    // O grant em lote, para todas, vale para as que já existem.
    const lote = tabelasDosTextos([...textos, "create table public.x (id bigserial);", "grant all on all sequences in schema public to service_role;"]);
    expect(semUso(lote.sequencias)).toEqual([]);
  }, 30_000);
});
