-- Arke: sincronização idempotente de pagamentos Asaas
create table if not exists public.asaas_webhook_events (
  id bigint generated by default as identity primary key,
  event_id text not null unique,
  event text not null,
  occurred_at timestamptz not null default now(),
  payload jsonb not null,
  created_at timestamptz not null default now()
);

create table if not exists public.asaas_payments (
  id bigint generated by default as identity primary key,
  asaas_id text not null unique,
  customer_id text,
  value numeric(12,2),
  billing_type text,
  due_date date,
  status text not null,
  invoice_url text,
  bank_slip_url text,
  raw_payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists asaas_payments_status_idx on public.asaas_payments(status);
create index if not exists asaas_payments_updated_at_idx on public.asaas_payments(updated_at desc);

alter table public.asaas_webhook_events enable row level security;
alter table public.asaas_payments enable row level security;

-- O backend usa a service_role para gravar e ler estes dados.
