import { useMemo, useState } from "react";
import { Check, CircleDollarSign, FileText, Pencil, Plus, RefreshCw, ShieldCheck, Trash2, Users } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { ORG_PLAN_AMOUNTS_CENTS, ORG_PLAN_KEYS, ORG_PLAN_LABELS, PLAN_AMOUNTS_CENTS, PROFISSIONAL_PLAN_AMOUNTS_CENTS, PROFISSIONAL_PLAN_KEYS, PROFISSIONAL_PLAN_LABELS, formatBRL, type SaasPlan } from "@shared/pricing";

const plans = [
  ...ORG_PLAN_KEYS.map((id) => ({ id, name: ORG_PLAN_LABELS[id], price: `${formatBRL(ORG_PLAN_AMOUNTS_CENTS[id])}/mês`, profile: "Academia/Studio" as const })),
  ...PROFISSIONAL_PLAN_KEYS.map((id) => ({ id, name: PROFISSIONAL_PLAN_LABELS[id], price: `${formatBRL(PROFISSIONAL_PLAN_AMOUNTS_CENTS[id])}/mês`, profile: "Profissional" as const })),
];
type PlanId = SaasPlan;
type Toast = { title: string; detail: string };
type Props = { tenantName: string; onTenantChange: (name: string) => void; onToast: (toast: Toast) => void };

const emptyOnboardingBenefits = { wellhubClientId: "", wellhubClientSecret: "", wellhubPartnerId: "", totalpassAppKey: "", totalpassAppSecret: "", totalpassGymId: "" };
const emptyOnboardingTurnstile = { brand: "", model: "", host: "", usuario: "", senha: "", apiKey: "" };
const TURNSTILE_BRAND_LABEL: Record<string, string> = { control_id: "Control iD", topdata: "Topdata", henry: "Henry", dimep: "Dimep", outra: "Outra" };

export default function SaasPage({ tenantName, onTenantChange, onToast }: Props) {
  const [selectedClientId, setSelectedClientId] = useState("");
  const [selectedPlan, setSelectedPlan] = useState<PlanId>("starter");
  const [workspaceSlug, setWorkspaceSlug] = useState("");
  const [brandColor, setBrandColor] = useState("#c99518");
  const [auditEntity, setAuditEntity] = useState("all");
  const [showCreate, setShowCreate] = useState(false);
  const [creatingWorkspace, setCreatingWorkspace] = useState(false);
  const [onboardingBenefits, setOnboardingBenefits] = useState(emptyOnboardingBenefits);
  const [onboardingTurnstile, setOnboardingTurnstile] = useState(emptyOnboardingTurnstile);
  const clients = trpc.admin.users.list.useQuery();
  const organizations = trpc.saas.organizations.list.useQuery();
  const selectedOrganization = organizations.data?.find(({ organization }) => organization.name === tenantName)?.organization;
  const realOrganizationId = selectedOrganization?.id;
  const access = trpc.saas.organizations.access.useQuery({ organizationId: realOrganizationId ?? "" }, { enabled: Boolean(realOrganizationId) });
  const audit = trpc.saas.organizations.audit.useQuery({ organizationId: realOrganizationId ?? "", entity: auditEntity }, { enabled: Boolean(realOrganizationId) });
  const deletionRequests = trpc.saas.organizations.listDeletionRequests.useQuery({ organizationId: realOrganizationId ?? "" }, { enabled: Boolean(realOrganizationId) });
  const utils = trpc.useUtils();
  const createWorkspace = trpc.saas.organizations.create.useMutation();
  const saveBenefitOnboarding = trpc.integracoes.beneficios.save.useMutation();
  const saveTurnstileOnboarding = trpc.integracoes.catraca.save.useMutation();
  const updatePlan = trpc.saas.organizations.updateSubscription.useMutation({ onSuccess: () => { onToast({ title: "Licença atualizada", detail: "Plano e limites persistidos no banco." }); utils.saas.organizations.list.invalidate(); }, onError: (error) => onToast({ title: "Erro ao atualizar licença", detail: error.message }) });
  const saveOnboarding = trpc.saas.organizations.saveOnboarding.useMutation({ onSuccess: () => onToast({ title: "Branding salvo", detail: "A configuração foi persistida na organização." }), onError: (error) => onToast({ title: "Erro ao salvar branding", detail: error.message }) });
  const createUnit = trpc.saas.organizations.createUnit.useMutation({ onSuccess: () => { onToast({ title: "Unidade criada", detail: "A unidade foi persistida no workspace." }); if (realOrganizationId) utils.saas.organizations.access.invalidate({ organizationId: realOrganizationId }); }, onError: (error) => onToast({ title: "Erro ao criar unidade", detail: error.message }) });
  const fulfillDeletion = trpc.saas.organizations.fulfillDeletionRequest.useMutation({ onSuccess: () => { onToast({ title: "Exclusão concluída", detail: "Os dados pessoais do aluno foram apagados." }); if (realOrganizationId) utils.saas.organizations.listDeletionRequests.invalidate({ organizationId: realOrganizationId }); }, onError: (error) => onToast({ title: "Erro ao concluir exclusão", detail: error.message }) });
  const rejectDeletion = trpc.saas.organizations.rejectDeletionRequest.useMutation({ onSuccess: () => { onToast({ title: "Solicitação recusada", detail: "O aluno foi mantido no sistema." }); if (realOrganizationId) utils.saas.organizations.listDeletionRequests.invalidate({ organizationId: realOrganizationId }); }, onError: (error) => onToast({ title: "Erro ao recusar solicitação", detail: error.message }) });
  const confirmFulfillDeletion = (requestId: string) => { if (!realOrganizationId) return; if (!window.confirm("Isso vai apagar de forma permanente o cadastro, treinos, planos alimentares, check-ins e acolhimento deste aluno. Continuar?")) return; fulfillDeletion.mutate({ organizationId: realOrganizationId, requestId }); };
  const confirmRejectDeletion = (requestId: string) => { if (!realOrganizationId) return; const note = window.prompt("Motivo da recusa (opcional)") ?? undefined; rejectDeletion.mutate({ organizationId: realOrganizationId, requestId, note: note || undefined }); };
  const mrr = (organizations.data ?? []).reduce((total, row) => total + (PLAN_AMOUNTS_CENTS[row.organization.plan] ?? 0) / 100, 0);
  const compatiblePlans = useMemo(() => { const module = clients.data?.find((item) => item.id === selectedClientId)?.module; return plans.filter((plan) => module === "profissional" ? plan.profile === "Profissional" : plan.profile === "Academia/Studio"); }, [clients.data, selectedClientId]);
  const submitCreate = async () => {
    const client = clients.data?.find((item) => item.id === selectedClientId);
    if (!client) return onToast({ title: "Selecione um cliente", detail: "O workspace exige um cliente cadastrado no banco." });
    if (!workspaceSlug.trim()) return onToast({ title: "Informe o slug", detail: "O slug identifica o acesso da organização." });
    setCreatingWorkspace(true);
    try {
      const result = await createWorkspace.mutateAsync({ clientId: client.id, module: client.module, name: client.name, slug: workspaceSlug.trim().toLowerCase(), plan: selectedPlan });
      if (onboardingBenefits.wellhubClientId || onboardingBenefits.wellhubClientSecret || onboardingBenefits.wellhubPartnerId) {
        await saveBenefitOnboarding.mutateAsync({ organizationId: result.organizationId, provider: "wellhub", enabled: true, fields: { client_id: onboardingBenefits.wellhubClientId, client_secret: onboardingBenefits.wellhubClientSecret, partner_id: onboardingBenefits.wellhubPartnerId } });
      }
      if (onboardingBenefits.totalpassAppKey || onboardingBenefits.totalpassAppSecret || onboardingBenefits.totalpassGymId) {
        await saveBenefitOnboarding.mutateAsync({ organizationId: result.organizationId, provider: "totalpass", enabled: true, fields: { app_key: onboardingBenefits.totalpassAppKey, app_secret: onboardingBenefits.totalpassAppSecret, gym_id: onboardingBenefits.totalpassGymId } });
      }
      if (onboardingTurnstile.brand) {
        await saveTurnstileOnboarding.mutateAsync({ organizationId: result.organizationId, unitId: result.unitId, brand: onboardingTurnstile.brand as "control_id" | "topdata" | "henry" | "dimep" | "outra", model: onboardingTurnstile.model || undefined, config: { host: onboardingTurnstile.host, usuario: onboardingTurnstile.usuario, senha: onboardingTurnstile.senha, api_key: onboardingTurnstile.apiKey }, enabled: true });
      }
      setShowCreate(false);
      setOnboardingBenefits(emptyOnboardingBenefits);
      setOnboardingTurnstile(emptyOnboardingTurnstile);
      onTenantChange(client.name);
      onToast({ title: "Workspace criado", detail: `Organização vinculada a ${client.name}, com benefícios e catraca já configurados quando informados.` });
      utils.saas.organizations.list.invalidate();
    } catch (error) {
      onToast({ title: "Não foi possível criar o workspace", detail: (error as Error).message });
    } finally {
      setCreatingWorkspace(false);
    }
  };
  const saveBranding = () => { if (!realOrganizationId) return onToast({ title: "Selecione uma licença", detail: "O branding precisa de uma organização ativa." }); saveOnboarding.mutate({ organizationId: realOrganizationId, currentStep: 4, status: "completed", defaultUnitName: selectedOrganization?.name, primaryColor: brandColor }); };
  const addUnit = () => { if (!realOrganizationId) return onToast({ title: "Selecione uma licença", detail: "A unidade precisa de um workspace ativo." }); const name = window.prompt("Nome da nova unidade"); if (!name?.trim()) return; createUnit.mutate({ organizationId: realOrganizationId, name: name.trim(), slug: name.trim().toLowerCase().replace(/[^a-z0-9]+/g, "-") }); };

  return <div className="mx-auto max-w-[1440px] p-5 sm:p-8"><div className="mb-7 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="mb-2 text-xs font-semibold uppercase tracking-[.16em] text-[#b08317]">administração SaaS</p><h2 className="text-3xl font-semibold tracking-[-.055em] text-[#231f18] sm:text-4xl">Licenças & planos</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-[#766f62]">Clientes, organizações, licenças, branding e unidades são carregados e persistidos no banco.</p></div><Button onClick={() => setShowCreate(true)} className="h-10 rounded-xl bg-[#15130f] px-4 text-xs font-semibold text-white"><Plus size={15} /> Criar workspace</Button></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi label="Licenças ativas" value={String(organizations.data?.filter(({ organization }) => ["trial", "active"].includes(organization.status)).length ?? 0)} icon={ShieldCheck} /><Kpi label="MRR" value={`R$ ${mrr.toLocaleString("pt-BR")}`} icon={CircleDollarSign} /><Kpi label="Clientes cadastrados" value={String(clients.data?.length ?? 0)} icon={Users} /><Kpi label="Unidades ativas" value={String(access.data?.units.length ?? 0)} icon={FileText} /></div>
    {showCreate && <Card className="mt-5 rounded-2xl border-[#e4dfd4] bg-[#fffdf9]"><CardHeader><CardTitle className="text-base">Novo workspace (onboarding)</CardTitle><p className="mt-1 text-xs text-[#918a7d]">É aqui que a implantação do cliente começa — inclui os benefícios e a catraca já usados por ele, quando informados agora.</p></CardHeader><CardContent className="grid gap-3 md:grid-cols-2"><select value={selectedClientId} onChange={(event) => { setSelectedClientId(event.target.value); const client = clients.data?.find((item) => item.id === event.target.value); const compatible = plans.find((plan) => client?.module === "profissional" ? plan.profile === "Profissional" : plan.profile === "Academia/Studio"); if (compatible) setSelectedPlan(compatible.id === "growth" || compatible.id === "scale" ? compatible.id : "starter"); }} className="h-10 rounded-xl border border-[#e2dcca] bg-white px-3 text-xs"><option value="">Selecione o cliente cadastrado</option>{(clients.data ?? []).filter((item) => item.module !== "aluno").map((item) => <option key={item.id} value={item.id}>{item.name} · {item.email}</option>)}</select><Input value={workspaceSlug} onChange={(event) => setWorkspaceSlug(event.target.value)} placeholder="slug-do-workspace" className="h-10 rounded-xl" /><select value={selectedPlan} onChange={(event) => setSelectedPlan(event.target.value as PlanId)} className="h-10 rounded-xl border border-[#e2dcca] bg-white px-3 text-xs">{(compatiblePlans.length ? compatiblePlans : plans).map((plan) => <option key={plan.id} value={plan.id}>{plan.name} · {plan.price}</option>)}</select>
      <div className="rounded-xl border border-dashed border-[#d8d0c0] p-3 md:col-span-2"><p className="mb-2 text-[10px] font-semibold uppercase tracking-[.14em] text-[#a47b13]">Benefícios (opcional — o cliente é o parceiro real da Wellhub/TotalPass)</p><div className="grid gap-2 md:grid-cols-3"><Input value={onboardingBenefits.wellhubClientId} onChange={(e) => setOnboardingBenefits({ ...onboardingBenefits, wellhubClientId: e.target.value })} placeholder="Wellhub · Client ID" className="h-9 rounded-lg text-xs" /><Input value={onboardingBenefits.wellhubClientSecret} onChange={(e) => setOnboardingBenefits({ ...onboardingBenefits, wellhubClientSecret: e.target.value })} placeholder="Wellhub · Client Secret" type="password" className="h-9 rounded-lg text-xs" /><Input value={onboardingBenefits.wellhubPartnerId} onChange={(e) => setOnboardingBenefits({ ...onboardingBenefits, wellhubPartnerId: e.target.value })} placeholder="Wellhub · Partner ID" className="h-9 rounded-lg text-xs" /><Input value={onboardingBenefits.totalpassAppKey} onChange={(e) => setOnboardingBenefits({ ...onboardingBenefits, totalpassAppKey: e.target.value })} placeholder="TotalPass · App Key" className="h-9 rounded-lg text-xs" /><Input value={onboardingBenefits.totalpassAppSecret} onChange={(e) => setOnboardingBenefits({ ...onboardingBenefits, totalpassAppSecret: e.target.value })} placeholder="TotalPass · App Secret" type="password" className="h-9 rounded-lg text-xs" /><Input value={onboardingBenefits.totalpassGymId} onChange={(e) => setOnboardingBenefits({ ...onboardingBenefits, totalpassGymId: e.target.value })} placeholder="TotalPass · Gym ID" className="h-9 rounded-lg text-xs" /></div></div>
      <div className="rounded-xl border border-dashed border-[#d8d0c0] p-3 md:col-span-2"><p className="mb-2 text-[10px] font-semibold uppercase tracking-[.14em] text-[#a47b13]">Catraca da unidade principal (opcional)</p><div className="grid gap-2 md:grid-cols-3"><select value={onboardingTurnstile.brand} onChange={(e) => setOnboardingTurnstile({ ...onboardingTurnstile, brand: e.target.value })} className="h-9 rounded-lg border bg-white px-2 text-xs"><option value="">Selecione a marca</option>{Object.entries(TURNSTILE_BRAND_LABEL).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><Input value={onboardingTurnstile.model} onChange={(e) => setOnboardingTurnstile({ ...onboardingTurnstile, model: e.target.value })} placeholder="Modelo" className="h-9 rounded-lg text-xs" /><Input value={onboardingTurnstile.host} onChange={(e) => setOnboardingTurnstile({ ...onboardingTurnstile, host: e.target.value })} placeholder="IP/host do equipamento" className="h-9 rounded-lg text-xs" /><Input value={onboardingTurnstile.usuario} onChange={(e) => setOnboardingTurnstile({ ...onboardingTurnstile, usuario: e.target.value })} placeholder="Usuário" className="h-9 rounded-lg text-xs" /><Input value={onboardingTurnstile.senha} onChange={(e) => setOnboardingTurnstile({ ...onboardingTurnstile, senha: e.target.value })} placeholder="Senha" type="password" className="h-9 rounded-lg text-xs" /><Input value={onboardingTurnstile.apiKey} onChange={(e) => setOnboardingTurnstile({ ...onboardingTurnstile, apiKey: e.target.value })} placeholder="API key (se houver)" type="password" className="h-9 rounded-lg text-xs" /></div></div>
      <div className="flex gap-2 md:col-span-2"><Button onClick={submitCreate} disabled={creatingWorkspace} className="h-10 rounded-xl bg-[#15130f] text-xs text-white">{creatingWorkspace ? "Criando..." : "Criar e vincular"}</Button><Button onClick={() => setShowCreate(false)} variant="outline" className="h-10 rounded-xl text-xs">Cancelar</Button></div></CardContent></Card>}
    <Card className="mt-5 rounded-2xl border-[#e4dfd4] bg-[#fffdf9]"><CardHeader className="flex flex-row items-center justify-between"><div><CardTitle className="text-base">Carteira de licenças</CardTitle><p className="mt-1 text-xs text-[#918a7d]">Cada linha representa uma organização real vinculada a um cliente.</p></div><Button onClick={() => organizations.refetch()} variant="outline" className="h-8 rounded-lg text-[11px]"><RefreshCw size={13} /> Atualizar</Button></CardHeader><CardContent className="space-y-2">{organizations.isLoading ? <p className="text-sm text-[#8b978e]">Carregando licenças...</p> : organizations.data?.length ? organizations.data.map(({ organization }) => <div key={organization.id} className="flex flex-col gap-3 rounded-2xl border border-[#eee9df] p-4 sm:flex-row sm:items-center"><div className="flex flex-1 items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#f4e8c9] text-xs font-bold text-[#946f14]">{organization.name.slice(0, 2).toUpperCase()}</div><div><p className="text-sm font-semibold text-[#413a2f]">{organization.name}</p><p className="mt-1 text-[11px] text-[#9b9488]">Plano {organization.plan} · {organization.status} · clientId {organization.client_id}</p></div></div><Button onClick={() => { onTenantChange(organization.name); setSelectedPlan((organization.plan === "growth" || organization.plan === "scale" ? organization.plan : "starter") as PlanId); }} className="h-8 rounded-lg bg-[#15130f] px-3 text-[11px] text-white"><Pencil size={13} /> Abrir</Button></div>) : <p className="rounded-xl bg-[#faf7ef] p-4 text-xs text-[#918a7d]">Nenhuma licença criada para os clientes cadastrados.</p>}</CardContent></Card>
    {realOrganizationId && <div className="mt-5 grid gap-5 lg:grid-cols-2"><Card className="rounded-2xl border-[#e4dfd4] bg-[#fffdf9]"><CardHeader><CardTitle className="text-base">Edição da licença ativa</CardTitle></CardHeader><CardContent className="space-y-3"><select value={selectedPlan} onChange={(event) => setSelectedPlan(event.target.value as PlanId)} className="h-10 w-full rounded-xl border border-[#e2dcca] bg-white px-3 text-xs">{plans.map((plan) => <option key={plan.id} value={plan.id}>{plan.name} · {plan.price}</option>)}</select><div className="flex gap-2"><Button onClick={() => updatePlan.mutate({ organizationId: realOrganizationId, plan: selectedPlan, status: "active" })} className="h-9 rounded-xl bg-[#15130f] text-xs text-white">Salvar plano</Button><Button onClick={addUnit} variant="outline" className="h-9 rounded-xl text-xs"><Plus size={14} /> Unidade</Button></div><div className="flex items-center gap-3"><input type="color" value={brandColor} onChange={(event) => setBrandColor(event.target.value)} className="h-9 w-12" /><Button onClick={saveBranding} variant="outline" className="h-9 rounded-xl text-xs">Salvar branding</Button></div></CardContent></Card><Card className="rounded-2xl border-[#e4dfd4] bg-[#fffdf9]"><CardHeader className="flex flex-row items-center justify-between"><CardTitle className="text-base">Auditoria</CardTitle><select value={auditEntity} onChange={(event) => setAuditEntity(event.target.value)} className="h-8 rounded-lg border border-[#e2dcca] bg-white px-2 text-[10px]"><option value="all">Todas as entidades</option><option value="subscription">Licença</option><option value="organization_unit">Unidade</option><option value="onboarding_branding">Branding</option></select></CardHeader><CardContent>{audit.isLoading ? <p className="text-xs text-[#918a7d]">Carregando auditoria...</p> : audit.data?.length ? <div className="space-y-2">{audit.data.slice(0, 8).map((entry) => <div key={entry.id} className="flex items-center justify-between rounded-lg bg-[#faf7ef] p-2.5"><span className="text-[10px] text-[#5d5548]">{entry.action} · {entry.entity}</span><span className="text-[10px] text-[#9b9488]">{new Date(entry.created_at).toLocaleString("pt-BR")}</span></div>)}</div> : <p className="text-xs text-[#918a7d]">Nenhum evento de auditoria para esta licença.</p>}</CardContent></Card>
      <Card className="rounded-2xl border-[#e4dfd4] bg-[#fffdf9] lg:col-span-2"><CardHeader><CardTitle className="text-base">Solicitações de exclusão de dados (LGPD)</CardTitle><p className="mt-1 text-xs text-[#918a7d]">Pedidos de exclusão feitos pelos próprios alunos desta organização. Concluir apaga o cadastro, treinos, planos alimentares, check-ins e acolhimento do aluno — não pode ser desfeito.</p></CardHeader><CardContent>
        {deletionRequests.isLoading ? <p className="text-xs text-[#918a7d]">Carregando solicitações...</p> : deletionRequests.data?.length ? <div className="space-y-2">{deletionRequests.data.map((item) => <div key={item.id} className="flex flex-col gap-2 rounded-lg bg-[#faf7ef] p-3 sm:flex-row sm:items-center sm:justify-between">
          <div><p className="text-xs font-semibold text-[#4b4438]">Aluno {item.user_id ?? "(conta já removida)"}</p><p className="mt-0.5 text-[10px] text-[#9b9488]">Solicitado em {new Date(item.requested_at).toLocaleString("pt-BR")} · status {item.status}{item.reason ? ` · motivo: ${item.reason}` : ""}</p></div>
          {item.status === "pending" && <div className="flex gap-2"><Button onClick={() => confirmFulfillDeletion(item.id)} disabled={fulfillDeletion.isPending} className="h-8 rounded-lg bg-[#b65343] px-3 text-[11px] text-white"><Trash2 size={13} /> Concluir exclusão</Button><Button onClick={() => confirmRejectDeletion(item.id)} disabled={rejectDeletion.isPending} variant="outline" className="h-8 rounded-lg px-3 text-[11px]">Recusar</Button></div>}
        </div>)}</div> : <p className="text-xs text-[#918a7d]">Nenhuma solicitação de exclusão para esta licença.</p>}
      </CardContent></Card>
    </div>}
  </div>;
}

function Kpi({ label, value, icon: Icon }: { label: string; value: string; icon: typeof Users }) { return <Card className="rounded-2xl border-[#e4dfd4] bg-[#fffdf9]"><CardContent className="p-5"><Icon size={18} className="text-[#a97f18]" /><p className="mt-5 text-xs text-[#938a7c]">{label}</p><p className="mt-1 text-2xl font-semibold text-[#332c20]">{value}</p></CardContent></Card>; }
