import { useMemo, useState } from "react";
import { Check, CircleDollarSign, FileText, Pencil, Plus, RefreshCw, ShieldCheck, Users } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";

const plans = [
  { id: "starter", name: "Starter", price: "R$ 399/mês", profile: "Academia/Studio" },
  { id: "growth", name: "Growth", price: "R$ 799/mês", profile: "Academia/Studio" },
  { id: "scale", name: "Scale", price: "R$ 1.490/mês", profile: "Academia/Studio" },
  { id: "unlimited", name: "Unlimited", price: "R$ 3.490/mês", profile: "Academia/Studio" },
  { id: "essencial", name: "Essencial", price: "R$ 149/mês", profile: "Profissional" },
  { id: "performance", name: "Performance", price: "R$ 249/mês", profile: "Profissional" },
  { id: "premium", name: "Premium", price: "R$ 199/mês", profile: "Profissional" },
] as const;
type PlanId = "starter" | "growth" | "scale" | "unlimited" | "essencial" | "performance" | "premium";
type Toast = { title: string; detail: string };
type Props = { tenantName: string; onTenantChange: (name: string) => void; onToast: (toast: Toast) => void };

export default function SaasPage({ tenantName, onTenantChange, onToast }: Props) {
  const [selectedClientId, setSelectedClientId] = useState("");
  const [selectedPlan, setSelectedPlan] = useState<PlanId>("starter");
  const [workspaceSlug, setWorkspaceSlug] = useState("");
  const [brandColor, setBrandColor] = useState("#c99518");
  const [auditEntity, setAuditEntity] = useState("all");
  const [showCreate, setShowCreate] = useState(false);
  const clients = trpc.admin.users.list.useQuery();
  const organizations = trpc.saas.organizations.list.useQuery();
  const selectedOrganization = organizations.data?.find(({ organization }) => organization.name === tenantName)?.organization;
  const realOrganizationId = selectedOrganization?.id;
  const access = trpc.saas.organizations.access.useQuery({ organizationId: realOrganizationId ?? "" }, { enabled: Boolean(realOrganizationId) });
  const audit = trpc.saas.organizations.audit.useQuery({ organizationId: realOrganizationId ?? "", entity: auditEntity }, { enabled: Boolean(realOrganizationId) });
  const utils = trpc.useUtils();
  const createWorkspace = trpc.saas.organizations.create.useMutation({ onSuccess: (result) => { const client = clients.data?.find((item) => item.id === selectedClientId); setShowCreate(false); if (client) onTenantChange(client.name); onToast({ title: "Workspace criado", detail: `Organização ${result.organizationId} vinculada ao cliente selecionado.` }); utils.saas.organizations.list.invalidate(); }, onError: (error) => onToast({ title: "Não foi possível criar o workspace", detail: error.message }) });
  const updatePlan = trpc.saas.organizations.updateSubscription.useMutation({ onSuccess: () => { onToast({ title: "Licença atualizada", detail: "Plano e limites persistidos no banco." }); utils.saas.organizations.list.invalidate(); }, onError: (error) => onToast({ title: "Erro ao atualizar licença", detail: error.message }) });
  const saveOnboarding = trpc.saas.organizations.saveOnboarding.useMutation({ onSuccess: () => onToast({ title: "Branding salvo", detail: "A configuração foi persistida na organização." }), onError: (error) => onToast({ title: "Erro ao salvar branding", detail: error.message }) });
  const createUnit = trpc.saas.organizations.createUnit.useMutation({ onSuccess: () => { onToast({ title: "Unidade criada", detail: "A unidade foi persistida no workspace." }); if (realOrganizationId) utils.saas.organizations.access.invalidate({ organizationId: realOrganizationId }); }, onError: (error) => onToast({ title: "Erro ao criar unidade", detail: error.message }) });
  const mrr = (organizations.data ?? []).reduce((total, row) => total + (plans.find((plan) => plan.id === row.organization.plan)?.id ? ({ starter: 399, growth: 799, scale: 1490, unlimited: 3490, essencial: 149, performance: 249, premium: 199 }[row.organization.plan] ?? 0) : 0), 0);
  const compatiblePlans = useMemo(() => { const module = clients.data?.find((item) => item.id === selectedClientId)?.module; return plans.filter((plan) => module === "profissional" ? plan.profile === "Profissional" : plan.profile === "Academia/Studio"); }, [clients.data, selectedClientId]);
  const submitCreate = () => { const client = clients.data?.find((item) => item.id === selectedClientId); if (!client) return onToast({ title: "Selecione um cliente", detail: "O workspace exige um cliente cadastrado no banco." }); if (!workspaceSlug.trim()) return onToast({ title: "Informe o slug", detail: "O slug identifica o acesso da organização." }); createWorkspace.mutate({ clientId: client.id, module: client.module, name: client.name, slug: workspaceSlug.trim().toLowerCase(), plan: selectedPlan }); };
  const saveBranding = () => { if (!realOrganizationId) return onToast({ title: "Selecione uma licença", detail: "O branding precisa de uma organização ativa." }); saveOnboarding.mutate({ organizationId: realOrganizationId, currentStep: 4, status: "completed", defaultUnitName: selectedOrganization?.name, primaryColor: brandColor }); };
  const addUnit = () => { if (!realOrganizationId) return onToast({ title: "Selecione uma licença", detail: "A unidade precisa de um workspace ativo." }); const name = window.prompt("Nome da nova unidade"); if (!name?.trim()) return; createUnit.mutate({ organizationId: realOrganizationId, name: name.trim(), slug: name.trim().toLowerCase().replace(/[^a-z0-9]+/g, "-") }); };

  return <div className="mx-auto max-w-[1440px] p-5 sm:p-8"><div className="mb-7 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="mb-2 text-xs font-semibold uppercase tracking-[.16em] text-[#b08317]">administração SaaS</p><h2 className="text-3xl font-semibold tracking-[-.055em] text-[#231f18] sm:text-4xl">Licenças & planos</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-[#766f62]">Clientes, organizações, licenças, branding e unidades são carregados e persistidos no banco.</p></div><Button onClick={() => setShowCreate(true)} className="h-10 rounded-xl bg-[#15130f] px-4 text-xs font-semibold text-white"><Plus size={15} /> Criar workspace</Button></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi label="Licenças ativas" value={String(organizations.data?.filter(({ organization }) => ["trial", "active"].includes(organization.status)).length ?? 0)} icon={ShieldCheck} /><Kpi label="MRR" value={`R$ ${mrr.toLocaleString("pt-BR")}`} icon={CircleDollarSign} /><Kpi label="Clientes cadastrados" value={String(clients.data?.length ?? 0)} icon={Users} /><Kpi label="Unidades ativas" value={String(access.data?.units.length ?? 0)} icon={FileText} /></div>
    {showCreate && <Card className="mt-5 rounded-2xl border-[#e4dfd4] bg-[#fffdf9]"><CardHeader><CardTitle className="text-base">Novo workspace</CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-2"><select value={selectedClientId} onChange={(event) => { setSelectedClientId(event.target.value); const client = clients.data?.find((item) => item.id === event.target.value); const compatible = plans.find((plan) => client?.module === "profissional" ? plan.profile === "Profissional" : plan.profile === "Academia/Studio"); if (compatible) setSelectedPlan(compatible.id === "growth" || compatible.id === "scale" ? compatible.id : "starter"); }} className="h-10 rounded-xl border border-[#e2dcca] bg-white px-3 text-xs"><option value="">Selecione o cliente cadastrado</option>{(clients.data ?? []).filter((item) => item.module !== "aluno").map((item) => <option key={item.id} value={item.id}>{item.name} · {item.email}</option>)}</select><Input value={workspaceSlug} onChange={(event) => setWorkspaceSlug(event.target.value)} placeholder="slug-do-workspace" className="h-10 rounded-xl" /><select value={selectedPlan} onChange={(event) => setSelectedPlan(event.target.value as PlanId)} className="h-10 rounded-xl border border-[#e2dcca] bg-white px-3 text-xs">{(compatiblePlans.length ? compatiblePlans : plans).map((plan) => <option key={plan.id} value={plan.id}>{plan.name} · {plan.price}</option>)}</select><div className="flex gap-2"><Button onClick={submitCreate} disabled={createWorkspace.isPending} className="h-10 rounded-xl bg-[#15130f] text-xs text-white">Criar e vincular</Button><Button onClick={() => setShowCreate(false)} variant="outline" className="h-10 rounded-xl text-xs">Cancelar</Button></div></CardContent></Card>}
    <Card className="mt-5 rounded-2xl border-[#e4dfd4] bg-[#fffdf9]"><CardHeader className="flex flex-row items-center justify-between"><div><CardTitle className="text-base">Carteira de licenças</CardTitle><p className="mt-1 text-xs text-[#918a7d]">Cada linha representa uma organização real vinculada a um cliente.</p></div><Button onClick={() => organizations.refetch()} variant="outline" className="h-8 rounded-lg text-[11px]"><RefreshCw size={13} /> Atualizar</Button></CardHeader><CardContent className="space-y-2">{organizations.isLoading ? <p className="text-sm text-[#8b978e]">Carregando licenças...</p> : organizations.data?.length ? organizations.data.map(({ organization }) => <div key={organization.id} className="flex flex-col gap-3 rounded-2xl border border-[#eee9df] p-4 sm:flex-row sm:items-center"><div className="flex flex-1 items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#f4e8c9] text-xs font-bold text-[#946f14]">{organization.name.slice(0, 2).toUpperCase()}</div><div><p className="text-sm font-semibold text-[#413a2f]">{organization.name}</p><p className="mt-1 text-[11px] text-[#9b9488]">Plano {organization.plan} · {organization.status} · clientId {organization.client_id}</p></div></div><Button onClick={() => { onTenantChange(organization.name); setSelectedPlan((organization.plan === "growth" || organization.plan === "scale" ? organization.plan : "starter") as PlanId); }} className="h-8 rounded-lg bg-[#15130f] px-3 text-[11px] text-white"><Pencil size={13} /> Abrir</Button></div>) : <p className="rounded-xl bg-[#faf7ef] p-4 text-xs text-[#918a7d]">Nenhuma licença criada para os clientes cadastrados.</p>}</CardContent></Card>
    {realOrganizationId && <div className="mt-5 grid gap-5 lg:grid-cols-2"><Card className="rounded-2xl border-[#e4dfd4] bg-[#fffdf9]"><CardHeader><CardTitle className="text-base">Edição da licença ativa</CardTitle></CardHeader><CardContent className="space-y-3"><select value={selectedPlan} onChange={(event) => setSelectedPlan(event.target.value as PlanId)} className="h-10 w-full rounded-xl border border-[#e2dcca] bg-white px-3 text-xs">{plans.map((plan) => <option key={plan.id} value={plan.id}>{plan.name} · {plan.price}</option>)}</select><div className="flex gap-2"><Button onClick={() => updatePlan.mutate({ organizationId: realOrganizationId, plan: selectedPlan, status: "active" })} className="h-9 rounded-xl bg-[#15130f] text-xs text-white">Salvar plano</Button><Button onClick={addUnit} variant="outline" className="h-9 rounded-xl text-xs"><Plus size={14} /> Unidade</Button></div><div className="flex items-center gap-3"><input type="color" value={brandColor} onChange={(event) => setBrandColor(event.target.value)} className="h-9 w-12" /><Button onClick={saveBranding} variant="outline" className="h-9 rounded-xl text-xs">Salvar branding</Button></div></CardContent></Card><Card className="rounded-2xl border-[#e4dfd4] bg-[#fffdf9]"><CardHeader className="flex flex-row items-center justify-between"><CardTitle className="text-base">Auditoria</CardTitle><select value={auditEntity} onChange={(event) => setAuditEntity(event.target.value)} className="h-8 rounded-lg border border-[#e2dcca] bg-white px-2 text-[10px]"><option value="all">Todas as entidades</option><option value="subscription">Licença</option><option value="organization_unit">Unidade</option><option value="onboarding_branding">Branding</option></select></CardHeader><CardContent>{audit.isLoading ? <p className="text-xs text-[#918a7d]">Carregando auditoria...</p> : audit.data?.length ? <div className="space-y-2">{audit.data.slice(0, 8).map((entry) => <div key={entry.id} className="flex items-center justify-between rounded-lg bg-[#faf7ef] p-2.5"><span className="text-[10px] text-[#5d5548]">{entry.action} · {entry.entity}</span><span className="text-[10px] text-[#9b9488]">{new Date(entry.created_at).toLocaleString("pt-BR")}</span></div>)}</div> : <p className="text-xs text-[#918a7d]">Nenhum evento de auditoria para esta licença.</p>}</CardContent></Card></div>}
  </div>;
}

function Kpi({ label, value, icon: Icon }: { label: string; value: string; icon: typeof Users }) { return <Card className="rounded-2xl border-[#e4dfd4] bg-[#fffdf9]"><CardContent className="p-5"><Icon size={18} className="text-[#a97f18]" /><p className="mt-5 text-xs text-[#938a7c]">{label}</p><p className="mt-1 text-2xl font-semibold text-[#332c20]">{value}</p></CardContent></Card>; }
